openapi: 3.0.1
info:
  title: powershell
  description: Microsoft Powershell Environment
  version: "1.0"
  x-direktiv-meta:
    container: gcr.io/direktiv/functions/powershell
    maintainer: "[direktiv.io](https://www.direktiv.io) "
    issues: https://github.com/direktiv-apps/powershell/issues
    url: https://github.com/direktiv-apps/powershell
    categories:
    - development
    - build
    license: "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)"
    long-description: |-
      This function has Powershell 7.2.6 installed plus the following plugins:
      - powershell-yaml
      - PSWriteHTML
      - Az
      - Posh-SSH

      For executing remote commands remoting has to be enabled on the target host. The following is an example of those settings. The `TrustedHosts` set to * is just for testing and should be more specific in production scenarios.

      `Enable-PSRemoting -Force`

      `Set-Item WSMan:\localhost\Client\TrustedHosts -Force -Value *`

      `Set-Service WinRM -StartMode Automatic`

      `Restart-Service -Force WinRM`

      Additionaly the firewall needs to be changed to allow traffic to the target host. In Direktiv it is recommended to set the attribute `size` to `large` because of a  bigger memory consumption of Powershell.
servers:
- url: /
paths:
  /:
    post:
      parameters:
      - name: Direktiv-ActionID
        in: header
        description: "direktiv action id is an UUID. \nFor development it can be set\
          \ to 'development'\n"
        schema:
          type: string
          default: development
      - name: Direktiv-TempDir
        in: header
        description: |
          direktiv temp dir is the working directory for that request
          For development it can be set to e.g. '/tmp'
        schema:
          type: string
          default: /tmp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: array
                  description: File to create before running commands.
                  items:
                    $ref: '#/components/schemas/direktivFile'
                commands:
                  type: array
                  description: Array of commands.
                  items:
                    type: object
                    properties:
                      command:
                        type: string
                        description: Command to run
                      silent:
                        type: boolean
                        description: If set to false the command will not print output
                          to logs.
                        default: false
                      print:
                        type: boolean
                        description: If set to false the command will not print the
                          full command with arguments to logs.
                        default: true
                      continue:
                        type: boolean
                        description: "Stops excecution if command fails, otherwise\
                          \ proceeds with next command"
        required: false
      responses:
        "200":
          description: List of executed Powershell commands.
          content:
            application/json:
              schema:
                type: object
                properties:
                  powershell:
                    type: array
                    items:
                      required:
                      - result
                      - success
                      type: object
                      properties:
                        success:
                          type: boolean
                        result:
                          type: object
            powershell:
              example:
                result:
                - Name: file1.txt
                - Name: file2.txt
                success: true
        default:
          description: generic error response
          headers:
            Direktiv-ErrorMessage:
              schema:
                type: string
            Direktiv-ErrorCode:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-direktiv-function: |-
        functions:
        - id: powershell
          image: gcr.io/direktiv/functions/powershell:1.0
          type: knative-workflow
          size: large
      x-direktiv-examples:
      - title: Run small script directly
        content: "- id: powershell \n  type: action\n  action:\n    function: powershell\n\
          \    files:\n    - key: script.ps1\n      scope: workflow\n    input: \n\
          \      files:\n      - name: script.ps1\n        data: |\n          Get-ChildItem\
          \ . | Select Name | ConvertTo-Json \n      commands:\n      - command: pwsh\
          \ script.ps1"
      - title: Run file
        content: "- id: powershell \n  type: action\n  action:\n    function: powershell\n\
          \    files:\n    - key: script.ps1\n      scope: workflow\n    input: \n\
          \      commands:\n      - command: pwsh script.ps1"
      x-direktiv:
        cmds:
        - action: foreach
          loop: .Commands
          exec: "{{ .Item.Command }}"
          silent: "{{ .Item.Silent }}"
          print: "{{ .Item.Print }}"
          continue: "{{ .Item.Continue }}"
        output: |
          {
            "powershell": {{ index . 0 | toJson }}
          }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      x-codegen-request-body-name: body
components:
  schemas:
    direktivFile:
      type: object
      x-go-type:
        type: DirektivFile
        import:
          package: github.com/direktiv/apps/go/pkg/apps
    error:
      required:
      - errorCode
      - errorMessage
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string

